"""Auto-generated by wikidata_enrich.py — height (P2048) from Wikidata."""

HEIGHTS = {
    "Jerry Bohlander": {"heightIn": 70.9, "displayHeight": "5' 11\""},
    "Joe Son": {"heightIn": 64.2, "displayHeight": "5' 4\""},
    "Marco Ruas": {"heightIn": 72.8, "displayHeight": "6' 1\""},
    "Marcus Jones": {"heightIn": 78.0, "displayHeight": "6' 6\""},
    "Mark Schultz": {"heightIn": 68.1, "displayHeight": "5' 8\""},
    "Royce Alger": {"heightIn": 66.1, "displayHeight": "5' 6\""},
    "Teila Tuli": {"heightIn": 74.0, "displayHeight": "6' 2\""},
    "Townsend Saunders": {"heightIn": 65.0, "displayHeight": "5' 5\""},
}
